### ISSUE TITLE
Geometry type (Point) does not match column type (MultiPoint)

### ISSUE THREAD

**Issue by Scorpion2115** [PacktPublishing/PostGIS-Cookbook-Second-Edition#11]
In step 4 and step 5 of chp3_R7.sql, I received an error `Geometry type (Point) does not match column type (MultiPoint)` when querying the table I created with MultiPoint geometry type. 

```sql
SELECT r1.gid AS gid1, r2.gid AS gid2,
      ST_Multi(ST_Intersection(r1.the_geom,
      r2.the_geom))::geometry(MultiPoint, 4326) AS the_geom
```

Shall we use `Geometry` instead of `MultiPoint` as the geometry type?
```sql
SELECT r1.gid AS gid1, r2.gid AS gid2,
      ST_Multi(ST_Intersection(r1.the_geom,
      r2.the_geom))::geometry(Geometry, 4326) AS the_geom
```

**Comment by smathermather** [comment]
Yes: I would expect the behavior of `MultiPoint` to take the assignment of a `Point`, but the behavior of PostGIS may have changed. Using the less restrictive `Geometry` makes sense here.

**Comment by Scorpion2115** [comment]
> Yes: I would expect the behavior of `MultiPoint` to take the assignment of a `Point`, but the behavior of PostGIS may have changed. Using the less restrictive `Geometry` makes sense here.

Thanks for your reply~
